language: generic
env:
  global:
  - CF_USERNAME=464f9db1-79d8-4ab5-b25c-b579369df7e8
  # CF_PASSWORD
  - secure: LaIT2cMvZ23V2QGF1R/9uY2RO8+bvnW5gbapDDZi7/bQKdDvqzdrlGZE/XUf5+zxX1itow/2H7BVDfkMnXwsILD+CrjQQbM2kdC14G63wB2Psg6kPv8hxtc07aOB6mO/QJHw8umL3NAwksDt9EW0JxAGnWM3T+afbhlugAfL34m+DP5Poy/EaC4+FHjuh04tlHNPlhaYs6A5LKScwREHT6KMl2dy6Q4qWAK1LATAbDLXcyEYY0Xg32y8kOg8767PIqQsOLdEtpZt1CW95cj9ZCEHLViKIjNckX/MxC1ybdcb5+IMPT+9PXn6Ogd15R8Px2PrTcdygKs/BKngKlr0BB4QrdpaX8j51rX4O78C9E1vy6tN3Uus7lK9TzKmrGI0aveykScSGD9IICpg1pCEiQRrO1h+ovVGM5pd0Hq47b0Z+nZR2ne+Csogle22TceCLnoX2Oq/zILIOk4I9eAemHCV6zuymQE+mOSSSi9IjVELYwn917NSOsR+fUxMK04V15sNLLY1DyceSlslLhXWQKzIyaPSVfglia/3uvsPjCLtGqq7W5gY7JefdyXB/xTf13vfAcwefQ8JvncfjRT4S2/6rMzKTu+UvsZ2bO+hD8ppt5WpRr3doD/RP4x402EkOCV/TCxTvOvRwMnXE38naixkBvLlGRykK2l9zpMMA6o=
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master
